### ISSUE TITLE
Player not Working in IE9

### ISSUE THREAD

**Issue by lemonhead** [videojs/videojs.com#32]
Hi,
the player is not working in IE9 on Windows 7. I'm using the v4.12.15 video.js from the cdn, but even on your website the error occurs:
SCRIPT16385: Not implemented
video.js, line 133 character 433
SCRIPT5007: Unable to get value of the property 'parse': object is null or undefined 
video.js, line 62 character 84

Could anyone please help? The link to my project is: http://projekte.lemonhead.de/u4-anim/ but at the moment the player is not even loading with the error.
I am using the player already in a customers project and it is necessary that it wors on IE9 and IE8 as well...

regards, lemonhead

**Comment by lemonhead** [comment]
Could please anybody help me with this problem???

**Comment by mister-ben** [comment]
Closing as this is the repo for the website and this is not a website issue. The main video.js repo is at https://github.com/videojs/video.js, but in this case it isn't really a video.js issue either so Stack Overflow might be a better resource.

The video doesn't play on IE9 because there is no source set. I can see how you're adding a source element to the video before instantiating the player, but for some reason appending source elements to video elements [doesn't work on IE9](http://stackoverflow.com/q/7174790/740233).

You could set the source with the video.js API when it's ready instead:

    player = videojs(containerId, {
      ...
      }, function(){
        this.src({src:"http://projekte.lemonhead.de/u4-anim/media/02_Gesamtanimation.mp4", type:"video/mp4"})
    });

**Comment by lemonhead** [comment]
Ok, thank you for the advise. I'll try this.
