### ISSUE TITLE
getting-started page uses wrong example code

### ISSUE THREAD

**Issue by vincentsijben** [videojs/videojs.com#99]
The first example on https://videojs.com/getting-started/ uses data-setup="{}" in the code example. That should be single quotes as stated in https://docs.videojs.com/tutorial-setup.html#automatic-setup.

The used https://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js file also returns a 403 (access denied) when used.

**Comment by gkatsev** [comment]
html attributes can be either single or double quotes, for consistency with the others, it's double quotes. It shouldn't matter in the case of an empty object. Once you start adding values then it matters, because JSON requires double quotes. We probably should just update it to be single quotes everywhere. Care to submit a PR? https://github.com/videojs/videojs.com/blob/master/_harp/getting-started/index.ejs#L64-L72

As for the ie8-version thing, this is because we do a replacement of the "ie8-version" value with a real value but the request to get the latest version must've failed. I thought we had a default value, but maybe not.

**Comment by vincentsijben** [comment]
HTML attributes actually dont need quotes (if no spaces in the value), but it is common to use it. I've tried to create a PR (first time). https://github.com/videojs/videojs.com/pull/100 hope this is ok.

How could I fix the ie8-version thingy?

**Comment by gkatsev** [comment]
yeah, not needed but nice for consistency and reduce potential issues :)

Looks like the issue was that we were reading the value from the video.js package.json as a dependency but in v7, we dropped the ie8 package as a dependency. I guess to fix it, we'd want to mirror the work in `vjs-version.js` https://github.com/videojs/videojs.com/blob/master/_src-js/lib/vjs-version.js but for ie8 and then use that value. Alternatively, we can hardcode the value at 1.1.2 as it's very unlikely to change again.
Actually, just hardcoding the value in sounds fine to me.
